"""admin, account, audit, settings

Revision ID: 3a195af8ebc0
Revises: 57307c344137
Create Date: 2026-06-14 02:59:56.362057
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a195af8ebc0'
down_revision: Union[str, None] = '57307c344137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_admin_id'), 'audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('auto_renew', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notes', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    op.drop_column('users', 'auto_renew')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_admin_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
