"""roles and 2fa

Revision ID: 4e586cc90290
Revises: 3a195af8ebc0
Create Date: 2026-06-14 03:14:51.561535
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e586cc90290'
down_revision: Union[str, None] = '3a195af8ebc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
