"""releases, flags, version stats, session epoch

Revision ID: 71a0713f8159
Revises: 2b8575ec5c73
Create Date: 2026-06-14 04:00:23.032869
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71a0713f8159'
down_revision: Union[str, None] = '2b8575ec5c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desktop_releases_created_at'), 'desktop_releases', ['created_at'], unique=False)
    op.create_index(op.f('ix_desktop_releases_version'), 'desktop_releases', ['version'], unique=False)
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rollout', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('version_stats',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.add_column('users', sa.Column('session_epoch', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_epoch')
    op.drop_table('version_stats')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_desktop_releases_version'), table_name='desktop_releases')
    op.drop_index(op.f('ix_desktop_releases_created_at'), table_name='desktop_releases')
    op.drop_table('desktop_releases')
    # ### end Alembic commands ###
